### ISSUE TITLE
Super Mario 3D World FGRP extraction issue.

### ISSUE THREAD

**Issue by SwiftieMuggle** [Gota7/Citric-Composer#1]
Hi there, im posting this issue here because i hope it can be fixed somehow.

Using Retsuko, i have been able to extract fwavs files and such from BFSAR files smoothly because this is the only tool i know that does it in ORDER and extracts FWAR files too.

But i have an issue with SM3DW for the Wii U, im trying to to extract FWAV files inside the FGRP that contains the sound effects and while it extracts, the tool does not extract ALL the sounds, it only extracts a few of them unlike vgmtoolbox for example. I would love for this to be fixed since retsuko extracts the files in the right order as they are stored in the container unlike other tools.

**Comment by Gota7** [comment]
Can you send the FGRP that only extracts a few, as well as a ZIP with the sounds that have been extracted?

**Comment by SwiftieMuggle** [comment]
sure.

this is what its extracted.

https://drive.google.com/open?id=12SW71RQhgHQ4HwWh7G9nVvshwPJNyIAq

this is the original file, its a sarc but theres a FGRP container inside.

https://drive.google.com/open?id=1iyXoCAILA9CyMYyU8GPpz_EOgirfEGeL

**Comment by Gota7** [comment]
Alright, fixed the issue. I incremented the position by 4s, which is problematic when the offset is not divisible by 4.
