### ISSUE TITLE
sound does not work

### ISSUE THREAD

**Issue by geilo667** [Gota7/Citric-Composer#8]
Hi, every time i try to replace a bfwav file in the original file and then try it on my switch, the whole music/sound is gone

**Comment by Gota7** [comment]
Try saving with no new changes and see if that works. If it does work, then that means the filesize of the new file you are putting in the game is too big or not saved in the proper version.

**Comment by geilo667** [comment]
I don't know how to save in another version

**Comment by Gota7** [comment]
Nice, good to hear.
