### ISSUE TITLE
bseq file not alterable inside of program

### ISSUE THREAD

**Issue by TopCape** [Gota7/Citric-Composer#9]
Hi, I'm not sure if this is intended, but when I try to alter directly from when I read a bcseq file, it doesn't save the change. When I try to save or export the file after I changed it, it saves the old original file instead (I verify this by using the replace function and replacing with the saved file, but the one replaced stays the same). If this isn't intentional would it be best to make it impossible to alter the text inside one when viewing it? Also, I don't know how to compile a bcseq to replace one in the program. After some observation I see that almost each entrance in a file has a specific name, sorry for not understanding quite how this project is made but I guess my problem is with Static's Sequencer, since that can read seq files? (This is in relation to a 3ds game btw, not sure of the different consoles and their formats)

Could someone please help?

**Comment by Gota7** [comment]
I don't think the BCSEQ editor can save. It was never complete, nor will it be.

Use my Sequence Convert program to convert BCSEQ to CSEQ (text), then convert it back to BCSEQ when you are done editing.
https://github.com/Gota7/SequenceConvert
